---
name: Server Health

'on':
  schedule:
    - cron: '*/30 * * * 1-5'  # Every 30 mins on weekdays
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check health endpoint
        run: |
          curl -fsSL "${{ vars.HEALTH_URL }}" || exit 1
